
CREATE SCHEMA IF NOT EXISTS testePHP_2018;

USE testePHP_2018;

CREATE TABLE IF NOT EXISTS clientes (
	id INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(255),
	email VARCHAR(255),
	endereco VARCHAR(255),
	data_cadastro DATE
);